spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: booking
          uri: http://article2-booking-service:8080
          predicates:
            - Path=/booking/**
        - id: financial
          uri: http://article2-financial-service:8080
          predicates:
            - Path=/financial/**
        - id: shell
          uri: http://article2-shell-service:8080
          predicates:
            - Path=/**