spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: booking
          uri: http://booking-ms:8080
          predicates:
            - Path=/booking/**
        - id: financial
          uri: http://financial-ms:8080
          predicates:
            - Path=/financial/**
        - id: shell
          uri: http://shell-ms:8080
          predicates:
            - Path=/**