server:
  port: 8083
spring:
  application:
    name: financial
  mongodb:
    database: financial
  kafka:
    bootstrap-servers:
      - http://localhost:9092
  cloud:
    function:
      definition: consumeAll
    stream:
      kafka:
        binder:
          brokers:
            - http://localhost:9092
      function:
        bindings:
          consumeAll-in-0: input
      bindings:
        input:
          destination: xx
          group: financial
        output:
          destination: xx
  logging:
    level:
      org.springframework.cloud.stream: INFO
      org.mongodb: INFO

