server:
  port: 8083
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/dev
    username: dev
    password: dev
#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/dev
#    username: dev
#    password: dev
#    pool:
#      enabled: true
  application:
    name: financial
  kafka:
    bootstrap-servers:
      - http://localhost:9092
  cloud:
    function:
      definition: consumeAll
    stream:
      kafka:
        binder:
          brokers:
            - http://localhost:9092
      function:
        bindings:
          consumeAll-in-0: input
      bindings:
        input:
          destination: xx
          group: financial
        output:
          destination: xx
  logging:
    level:
      org.springframework.cloud.stream: INFO
      org.mongodb: INFO
  jooq:
    sql-dialect: mariadb
logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG