server:
  port: 8080
spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/dev
#    username: dev
#    password: dev
  r2dbc:
    url: r2dbc:mariadb://mariadb:3306/prod
    username: prod
    password: prod
    pool:
      enabled: true
  liquibase:
    url: jdbc:mariadb://mariadb:3306/prod
    password: prod
    user: prod
  application:
    name: financial
  kafka:
    bootstrap-servers:
      - http://kafka:9092
  cloud:
    function:
      definition: consumeAllForInvoice;consumeAllForBooking
    stream:
      kafka:
        binder:
          brokers:
            - http://kafka:9092
      function:
        bindings:
          consumeAllForBooking-in-0: input-booking
          consumeAllForInvoice-in-0: input-invoice
      bindings:
        input-booking:
          destination: xx
          group: financial-booking
        input-invoice:
          destination: xx
          group: financial-invoice
        output:
          destination: xx
  logging:
    level:
      org.springframework.cloud.stream: INFO
      org:
        jooq:
          tools:
            LoggerListener: debug
  jooq:
    sql-dialect: mariadb
logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: debug
