/*
 * This file is generated by jOOQ.
 */
package io.mateu.article2.cqrssink.infra.secondary.jooq.model.default_schema;


import io.mateu.article2.cqrssink.infra.secondary.jooq.model.default_schema.tables.Booking;
import io.mateu.article2.cqrssink.infra.secondary.jooq.model.default_schema.tables.records.BookingRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BookingRecord> PK_BOOKING = Internal.createUniqueKey(Booking.BOOKING, DSL.name("PK_BOOKING"), new TableField[] { Booking.BOOKING.ID }, true);
}
