/*
 * This file is generated by jOOQ.
 */
package io.mateu.article2.cqrssink.infra.secondary.jooq.model.default_schema;


import io.mateu.article2.cqrssink.infra.secondary.jooq.model.default_schema.tables.Booking;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>BOOKING</code>.
     */
    public static final Booking BOOKING = Booking.BOOKING;
}
