/*
 * This file is generated by jOOQ.
 */
package io.mateu.article2.cqrssink.infra.secondary.jooq.model.default_schema.tables.records;


import io.mateu.article2.cqrssink.infra.secondary.jooq.model.default_schema.tables.Booking;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookingRecord extends UpdatableRecordImpl<BookingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>BOOKING.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>BOOKING.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>BOOKING.CUSTOMER</code>.
     */
    public void setCustomer(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>BOOKING.CUSTOMER</code>.
     */
    public String getCustomer() {
        return (String) get(1);
    }

    /**
     * Setter for <code>BOOKING.SERVICE</code>.
     */
    public void setService(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>BOOKING.SERVICE</code>.
     */
    public String getService() {
        return (String) get(2);
    }

    /**
     * Setter for <code>BOOKING.START_DATE</code>.
     */
    public void setStartDate(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>BOOKING.START_DATE</code>.
     */
    public String getStartDate() {
        return (String) get(3);
    }

    /**
     * Setter for <code>BOOKING.END_DATE</code>.
     */
    public void setEndDate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>BOOKING.END_DATE</code>.
     */
    public String getEndDate() {
        return (String) get(4);
    }

    /**
     * Setter for <code>BOOKING.VALUE</code>.
     */
    public void setValue(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>BOOKING.VALUE</code>.
     */
    public BigDecimal getValue() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>BOOKING.STATUS</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>BOOKING.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    /**
     * Setter for <code>BOOKING.INVOICED</code>.
     */
    public void setInvoiced(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>BOOKING.INVOICED</code>.
     */
    public BigDecimal getInvoiced() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>BOOKING.PAID</code>.
     */
    public void setPaid(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>BOOKING.PAID</code>.
     */
    public BigDecimal getPaid() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>BOOKING.SEARCHABLE_TEXT</code>.
     */
    public void setSearchableText(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>BOOKING.SEARCHABLE_TEXT</code>.
     */
    public String getSearchableText() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookingRecord
     */
    public BookingRecord() {
        super(Booking.BOOKING);
    }

    /**
     * Create a detached, initialised BookingRecord
     */
    public BookingRecord(String id, String customer, String service, String startDate, String endDate, BigDecimal value, String status, BigDecimal invoiced, BigDecimal paid, String searchableText) {
        super(Booking.BOOKING);

        setId(id);
        setCustomer(customer);
        setService(service);
        setStartDate(startDate);
        setEndDate(endDate);
        setValue(value);
        setStatus(status);
        setInvoiced(invoiced);
        setPaid(paid);
        setSearchableText(searchableText);
        resetChangedOnNotNull();
    }
}
