/*
 * This file is generated by jOOQ.
 */
package io.mateu.article2.financial.jooq.model.default_schema;


import io.mateu.article2.financial.jooq.model.default_schema.tables.Booking;
import io.mateu.article2.financial.jooq.model.default_schema.tables.Event;
import io.mateu.article2.financial.jooq.model.default_schema.tables.Invoice;
import io.mateu.article2.financial.jooq.model.default_schema.tables.Payment;
import io.mateu.article2.financial.jooq.model.default_schema.tables.records.BookingRecord;
import io.mateu.article2.financial.jooq.model.default_schema.tables.records.EventRecord;
import io.mateu.article2.financial.jooq.model.default_schema.tables.records.InvoiceRecord;
import io.mateu.article2.financial.jooq.model.default_schema.tables.records.PaymentRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BookingRecord> PK_BOOKING = Internal.createUniqueKey(Booking.BOOKING, DSL.name("PK_BOOKING"), new TableField[] { Booking.BOOKING.ID }, true);
    public static final UniqueKey<EventRecord> PK_EVENT = Internal.createUniqueKey(Event.EVENT, DSL.name("PK_EVENT"), new TableField[] { Event.EVENT.ID }, true);
    public static final UniqueKey<InvoiceRecord> PK_INVOICE = Internal.createUniqueKey(Invoice.INVOICE, DSL.name("PK_INVOICE"), new TableField[] { Invoice.INVOICE.ID }, true);
    public static final UniqueKey<PaymentRecord> PK_PAYMENT = Internal.createUniqueKey(Payment.PAYMENT, DSL.name("PK_PAYMENT"), new TableField[] { Payment.PAYMENT.ID }, true);
}
