/*
 * This file is generated by jOOQ.
 */
package io.mateu.article2.financial.jooq.model.default_schema;


import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable;
import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable2;
import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable3;
import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable4;
import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable5;
import io.mateu.article2.financial.jooq.model.default_schema.tables.records.TestTable2Record;
import io.mateu.article2.financial.jooq.model.default_schema.tables.records.TestTable3Record;
import io.mateu.article2.financial.jooq.model.default_schema.tables.records.TestTable4Record;
import io.mateu.article2.financial.jooq.model.default_schema.tables.records.TestTable5Record;
import io.mateu.article2.financial.jooq.model.default_schema.tables.records.TestTableRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TestTableRecord> PK_TEST_TABLE = Internal.createUniqueKey(TestTable.TEST_TABLE, DSL.name("PK_TEST_TABLE"), new TableField[] { TestTable.TEST_TABLE.TEST_COLUMN }, true);
    public static final UniqueKey<TestTable2Record> PK_TEST_TABLE2 = Internal.createUniqueKey(TestTable2.TEST_TABLE2, DSL.name("PK_TEST_TABLE2"), new TableField[] { TestTable2.TEST_TABLE2.TEST_COLUMN }, true);
    public static final UniqueKey<TestTable3Record> PK_TEST_TABLE3 = Internal.createUniqueKey(TestTable3.TEST_TABLE3, DSL.name("PK_TEST_TABLE3"), new TableField[] { TestTable3.TEST_TABLE3.TEST_COLUMN }, true);
    public static final UniqueKey<TestTable4Record> PK_TEST_TABLE4 = Internal.createUniqueKey(TestTable4.TEST_TABLE4, DSL.name("PK_TEST_TABLE4"), new TableField[] { TestTable4.TEST_TABLE4.TEST_COLUMN }, true);
    public static final UniqueKey<TestTable5Record> PK_TEST_TABLE5 = Internal.createUniqueKey(TestTable5.TEST_TABLE5, DSL.name("PK_TEST_TABLE5"), new TableField[] { TestTable5.TEST_TABLE5.TEST_COLUMN }, true);
}
