/*
 * This file is generated by jOOQ.
 */
package io.mateu.article2.financial.jooq.model.default_schema;


import io.mateu.article2.financial.jooq.model.default_schema.tables.Booking;
import io.mateu.article2.financial.jooq.model.default_schema.tables.Event;
import io.mateu.article2.financial.jooq.model.default_schema.tables.Invoice;
import io.mateu.article2.financial.jooq.model.default_schema.tables.Payment;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>BOOKING</code>.
     */
    public static final Booking BOOKING = Booking.BOOKING;

    /**
     * The table <code>EVENT</code>.
     */
    public static final Event EVENT = Event.EVENT;

    /**
     * The table <code>INVOICE</code>.
     */
    public static final Invoice INVOICE = Invoice.INVOICE;

    /**
     * The table <code>PAYMENT</code>.
     */
    public static final Payment PAYMENT = Payment.PAYMENT;
}
