/*
 * This file is generated by jOOQ.
 */
package io.mateu.article2.financial.jooq.model.default_schema;


import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable;
import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable2;
import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable3;
import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable4;
import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable5;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>TEST_TABLE</code>.
     */
    public static final TestTable TEST_TABLE = TestTable.TEST_TABLE;

    /**
     * The table <code>TEST_TABLE2</code>.
     */
    public static final TestTable2 TEST_TABLE2 = TestTable2.TEST_TABLE2;

    /**
     * The table <code>TEST_TABLE3</code>.
     */
    public static final TestTable3 TEST_TABLE3 = TestTable3.TEST_TABLE3;

    /**
     * The table <code>TEST_TABLE4</code>.
     */
    public static final TestTable4 TEST_TABLE4 = TestTable4.TEST_TABLE4;

    /**
     * The table <code>TEST_TABLE5</code>.
     */
    public static final TestTable5 TEST_TABLE5 = TestTable5.TEST_TABLE5;
}
