server:
  port: 8082
spring:
  application:
    name: booking
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/dev
    username: dev
    password: dev
    pool:
      enabled: true
  mongodb:
    database: booking
  kafka:
    bootstrap-servers:
      - http://localhost:9092
  cloud:
    function:
      definition: consumeAll
    stream:
      kafka:
        binder:
          brokers:
            - http://localhost:9092
      function:
        bindings:
          consumeAll-in-0: input
      bindings:
        input:
          destination: xx
          group: booking
        output:
          destination: xx
  logging:
    level:
      org.springframework.cloud.stream: INFO
      org.mongodb: INFO
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
