server:
  port: 8080
spring:
  application:
    name: booking
  r2dbc:
    url: r2dbc:postgresql://postgres-postgresql.default.svc.cluster.local:5432/prod
    username: postgres
    password: UeZVplt9D8
    pool:
      enabled: true
  data:
    mongodb:
      username: prod
      password: prod
      host: mongo-mongodb.default.svc.cluster.local
      port: 27017
      database: booking
  kafka:
    bootstrap-servers:
      - http://kafka:9092
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="user1" password="CAachaB7ZA";
  cloud:
    function:
      definition: consumeAll
    stream:
      kafka:
        binder:
          brokers:
            - http://kafka:9092
      function:
        bindings:
          consumeAll-in-0: input
      bindings:
        input:
          destination: xx
          group: booking
        output:
          destination: xx
  logging:
    level:
      org.springframework.cloud.stream: INFO
      org.mongodb: INFO
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
