server:
  port: 8084
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: dev
    password: dev
    pool:
      enabled: true
  application:
    name: cqrs-sink
  kafka:
    bootstrap-servers:
      - http://localhost:9092
  cloud:
    function:
      definition: consumeAll
    stream:
      kafka:
        binder:
          brokers:
            - http://localhost:9092
      function:
        bindings:
          consumeAll-in-0: input
      bindings:
        input:
          destination: xx
          group: cqrs-sink
        output:
          destination: xx
  logging:
    level:
      org.springframework.cloud.stream: INFO
      org.mongodb: INFO
  jooq:
    sql-dialect: postgres
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
      jooq:
        Constants: WARN
        tools:
          LoggerListener: DEBUG
