/*
 * This file is generated by jOOQ.
 */
package io.mateu.article2.financial.jooq.model.default_schema.tables.records;


import io.mateu.article2.financial.jooq.model.default_schema.tables.Booking;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BookingRecord extends UpdatableRecordImpl<BookingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>BOOKING.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>BOOKING.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>BOOKING._VALUE</code>.
     */
    public void set_Value(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>BOOKING._VALUE</code>.
     */
    public BigDecimal get_Value() {
        return (BigDecimal) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookingRecord
     */
    public BookingRecord() {
        super(Booking.BOOKING);
    }

    /**
     * Create a detached, initialised BookingRecord
     */
    public BookingRecord(String id, BigDecimal _Value) {
        super(Booking.BOOKING);

        setId(id);
        set_Value(_Value);
        resetChangedOnNotNull();
    }
}
