/*
 * This file is generated by jOOQ.
 */
package io.mateu.article2.financial.jooq.model.default_schema.tables.records;


import io.mateu.article2.financial.jooq.model.default_schema.tables.Payment;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PaymentRecord extends UpdatableRecordImpl<PaymentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>PAYMENT.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PAYMENT.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PAYMENT.BOOKING_ID</code>.
     */
    public void setBookingId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PAYMENT.BOOKING_ID</code>.
     */
    public String getBookingId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PAYMENT._DATE</code>.
     */
    public void set_Date(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>PAYMENT._DATE</code>.
     */
    public LocalDate get_Date() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>PAYMENT._VALUE</code>.
     */
    public void set_Value(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>PAYMENT._VALUE</code>.
     */
    public BigDecimal get_Value() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentRecord
     */
    public PaymentRecord() {
        super(Payment.PAYMENT);
    }

    /**
     * Create a detached, initialised PaymentRecord
     */
    public PaymentRecord(String id, String bookingId, LocalDate _Date, BigDecimal _Value) {
        super(Payment.PAYMENT);

        setId(id);
        setBookingId(bookingId);
        set_Date(_Date);
        set_Value(_Value);
        resetChangedOnNotNull();
    }
}
