/*
 * This file is generated by jOOQ.
 */
package io.mateu.article2.financial.jooq.model.default_schema.tables.records;


import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable3;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestTable3Record extends UpdatableRecordImpl<TestTable3Record> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TEST_TABLE3.TEST_COLUMN</code>.
     */
    public void setTestColumn(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TEST_TABLE3.TEST_COLUMN</code>.
     */
    public Integer getTestColumn() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestTable3Record
     */
    public TestTable3Record() {
        super(TestTable3.TEST_TABLE3);
    }

    /**
     * Create a detached, initialised TestTable3Record
     */
    public TestTable3Record(Integer testColumn) {
        super(TestTable3.TEST_TABLE3);

        setTestColumn(testColumn);
        resetChangedOnNotNull();
    }
}
