/*
 * This file is generated by jOOQ.
 */
package io.mateu.article2.financial.jooq.model.default_schema.tables.records;


import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable5;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestTable5Record extends UpdatableRecordImpl<TestTable5Record> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TEST_TABLE5.TEST_COLUMN</code>.
     */
    public void setTestColumn(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>TEST_TABLE5.TEST_COLUMN</code>.
     */
    public String getTestColumn() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestTable5Record
     */
    public TestTable5Record() {
        super(TestTable5.TEST_TABLE5);
    }

    /**
     * Create a detached, initialised TestTable5Record
     */
    public TestTable5Record(String testColumn) {
        super(TestTable5.TEST_TABLE5);

        setTestColumn(testColumn);
        resetChangedOnNotNull();
    }
}
