/*
 * This file is generated by jOOQ.
 */
package io.mateu.article2.financial.jooq.model.default_schema.tables.records;


import io.mateu.article2.financial.jooq.model.default_schema.tables.TestTable;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestTableRecord extends UpdatableRecordImpl<TestTableRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>TEST_TABLE.TEST_COLUMN</code>.
     */
    public void setTestColumn(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>TEST_TABLE.TEST_COLUMN</code>.
     */
    public Integer getTestColumn() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TestTableRecord
     */
    public TestTableRecord() {
        super(TestTable.TEST_TABLE);
    }

    /**
     * Create a detached, initialised TestTableRecord
     */
    public TestTableRecord(Integer testColumn) {
        super(TestTable.TEST_TABLE);

        setTestColumn(testColumn);
        resetChangedOnNotNull();
    }
}
